[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-audit --no-fund"
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/schema.prisma"]
